# -*- coding: utf-8 -*-
"""598663 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0qqeVROXvRXMNNFYPe2vMhV3ukTum6g
"""

!pip install transformers sentence-transformers matplotlib

import torch
import random
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image
import requests
from io import BytesIO

from transformers import BlipProcessor, BlipForConditionalGeneration
from sentence_transformers import SentenceTransformer, util

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

blip_processor = BlipProcessor.from_pretrained(
    "Salesforce/blip-image-captioning-base"
)

blip_model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
).to(device)

sbert = SentenceTransformer("all-MiniLM-L6-v2")

image_urls = [
    "https://images.unsplash.com/photo-1518791841217-8f162f1e1131",
    "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d",
    "https://images.unsplash.com/photo-1492724441997-5dc865305da7",
    "https://images.unsplash.com/photo-1507149833265-60c372daea22",
    "https://images.unsplash.com/photo-1517849845537-4d257902454a"
] * 20

def load_image(url):
    response = requests.get(url)
    return Image.open(BytesIO(response.content)).convert("RGB")

def generate_caption(image):
    inputs = blip_processor(
        image,
        return_tensors="pt"
    ).to(device)

    out = blip_model.generate(
        **inputs,
        max_new_tokens=20
    )

    return blip_processor.decode(
        out[0],
        skip_special_tokens=True
    )

def inject_fault(text):
    words = text.split()

    replacement_words = [
        "dog",
        "car",
        "tree",
        "person",
        "building",
        "bicycle",
        "cat"
    ]

    if len(words) > 3:
        idx = random.randint(0, len(words) - 1)
        words[idx] = random.choice(replacement_words)

    return " ".join(words)

def compute_similarity(c1, c2):
    emb1 = sbert.encode(
        c1,
        convert_to_tensor=True
    )

    emb2 = sbert.encode(
        c2,
        convert_to_tensor=True
    )

    return util.cos_sim(
        emb1,
        emb2
    ).item()

threshold = 0.7

baseline_scores = []
framework_scores = []

fault_detected = 0
total_faults = 0

for i, url in enumerate(image_urls):

    image = load_image(url)

    generator_caption = generate_caption(image)

    verifier_caption = inject_fault(
        generator_caption
    )

    similarity = compute_similarity(
        generator_caption,
        verifier_caption
    )

    baseline_similarity = compute_similarity(
        generator_caption,
        generator_caption
    )

    framework_scores.append(similarity)
    baseline_scores.append(baseline_similarity)

    fault = similarity < threshold

    total_faults += 1

    if fault:
        fault_detected += 1

    print("Image:", i + 1)
    print("Generator:", generator_caption)
    print("Verifier :", verifier_caption)
    print("Similarity:", round(similarity, 3))
    print("Fault Detected:", fault)
    print("------")

framework_scores = np.array(framework_scores)
baseline_scores = np.array(baseline_scores)

print("\n===== BASELINE RESULTS =====")
print("Baseline Mean:", round(baseline_scores.mean(), 3))
print("Baseline Std :", round(baseline_scores.std(), 3))

print("\n===== FRAMEWORK RESULTS =====")
print("Framework Mean:", round(framework_scores.mean(), 3))
print("Framework Std :", round(framework_scores.std(), 3))
print("Framework Min :", round(framework_scores.min(), 3))
print("Framework Max :", round(framework_scores.max(), 3))

accuracy = fault_detected / total_faults

print("\n===== FAULT DETECTION =====")
print("Fault Detection Accuracy:", round(accuracy, 3))

plt.figure(figsize=(8, 5))

plt.hist(
    baseline_scores,
    bins=10,
    alpha=0.6,
    label="Baseline"
)

plt.hist(
    framework_scores,
    bins=10,
    alpha=0.6,
    label="Framework"
)

plt.axvline(
    x=threshold,
    linestyle="--",
    label="Threshold"
)

plt.xlabel("Semantic Similarity")
plt.ylabel("Frequency")
plt.title("Baseline vs Self-Checking Framework")

plt.legend()

plt.show()